name: PR metadata annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates pull request with metadata
    steps:
      - name: Get data from the database
        run: |
          echo docker run --name controller-container --entrypoint="./controller/build/searchseco" -e "github_token=${{secrets.GITHUB_TOKEN}}" -e "worker_name=GekkeHarrie" searchseco/controller check https://github.com/SecureSECO/SearchSECOController
        
      - name: Annotate PR
        uses: JarnoHendriksen/github-actions-test@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
