name: Check licenses with Tortellini

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    tortellini:
        uses: JarnoHendriksen/test/.github/workflows/main.yml@main
