name: Check licenses with Tortellini

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    tortellini:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: JarnoHendriksen/test/.github/workflows/tortellini.yml@main
